# Uncomment this line to define a global platform for your project
platform :ios, ‘7.0’
# Uncomment this line if you're using Swift
# use_frameworks!

target 'LPRefreshControl' do
pod 'SVPullToRefresh', '~> 0.4.1'
end

